version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks: 
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    depends_on:
      es01:
        condition: service_started
    networks: 
      - elastic
    ports:
      - 5601:5601
networks:
  elastic:
    driver: bridge
